spring:

  mvc:
    static-path-pattern: /static/**

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  resources:
    static-locations:
      - classpath:/static/
    cache:
      period: 0

  http:
    encoding:
      charset: UTF-8

    multipart:
      enabled=false: false

server:
  port: 8080
  servlet:
    context-path: /
    multipart:
      file-size-threshold: 512MB
      location: C:/Temp/
      max-file-size: 10MB
      max-request-size: 50MB
  session:
    timeout: 1

logging:
  exception-conversion-word: '%wEx'
  charset: UTF-8
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}){green} %clr(${PID:- }){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    web: debug